config/routes.rb
Rails.application.routes.draw do
  resources :projects, only: [:new, :create] do
    get :download_count, on: :collection
  end

  root 'projects#new'
end

app/models/download.rb
class Download < ApplicationRecord
  validates :app_type, :rails_version, :ruby_version, :database, presence: true

  def self.total_count
    count
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def new
    @supported_rails_versions = %w[7.0 6.1].freeze
    @supported_ruby_versions = %w[3.2.2 3.1.4 3.0.6 2.7.8].freeze
    @supported_databases = %w[sqlite mysql postgresql].freeze
    @supported_app_types = ::ProjectCreator::APP_TYPES.keys.freeze
    # @supported_js_processors = %w[importmap webpack esbuild rollup].freeze
    # @supported_css_processors = %w[tailwind bootstrap bulma postcss sass].freeze
  end

  def create
    zip_file_path = ::ProjectCreator.new(
      app_type: params[:app_type].presence || 'standard',
      rails_version: params[:rails_version].presence || '7.0',
      ruby_version: params[:ruby_version].presence || '3.2.2',
      database: params[:database].presence || 'sqlite',
    ).call

    send_file zip_file_path, type: 'application/zip', disposition: 'attachment', filename: 'project.zip'
  end

  def download_count
    count = Download.total_count
    render json: { count: count }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def default_meta_tags
    site = 'www.railsinit.org'
    title = 'Rails Initializer'
    description = 'Create a new Rails app from your browser! Select your configurations in just a few clicks, and launch your Rails journey with ease and speed. Get building now!'
    image_height = 630
    image_width = 1200
    {
      site: site,
      title: title,
      reverse: true,
      separator: '|',
      description: description,
      keywords: 'rails initializer, rails, ruby on rails, rails init, rails generator, rails app generator, rails initializr, ruby',
      canonical: site,
      noindex: !Rails.env.production?,
      index: true,
      author: 'Phillip Musiime',
      icon: [
        { href: image_url('favicon.ico') },
        { href: image_url('rails-init-logo.png'), rel: 'apple-touch-icon', sizes: '180x180', type: 'image/jpg' },
      ],
      og: {
        site_name: site,
        title: title,
        description: description,
        type: 'website',
        url: request.original_url,
        image: {
          _: image_url('logo.png'),
          alt: 'rails initilaizer logo',
          type: 'image/png',
          width: image_width,
          height: image_height,
        }
      },
      twitter: {
        card: 'summary_large_image',
        site: '@Phillip_Ug',
        creator: '@Phillip_Ug',
        title: title,
        description: description,
        image: {
          _: image_url('logo.png'),
          height: image_height,
          width: image_width
        }
      }
    }
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/_google_analytics.html.erb
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-6E66BZ0GY7"></script>
<script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'G-6E66BZ0GY7');
</script>

app/views/layouts/_header.html.erb
<header class="h-fit fixed top-0 left-0 right-0 z-10 bg-white px-6 py-3 flex items-center justify-between shadow-md over">
  <div class="max-w-[300px] min-w-[250px]">
    <a href="/">
      <%= image_tag(image_path('logo.png')) %>
    </a>
  </div>

  <div>
    <p><span class="text-lg md:text-2xl text-gray-400">Downloads: </span> <span class="inline-block w-full text-center md:inline text-2xl text-red-900 font-extrabold" id="downloads"><%= Download.count %></span> </p>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-full bg-white">
  <head>
    <%= render 'layouts/google_analytics' if Rails.env.production? %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= display_meta_tags(default_meta_tags) %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

    <%= favicon_link_tag 'favicon.ico' %>
  </head>

  <body class="h-full overflow-hidden">
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/projects/_info.html.erb
<div class="rounded-md bg-blue-50 p-4 mt-2">
  <div class="flex">
    <div class="flex-shrink-0">
      <svg class="h-5 w-5 text-blue-400" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
        <path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a.75.75 0 000 1.5h.253a.25.25 0 01.244.304l-.459 2.066A1.75 1.75 0 0010.747 15H11a.75.75 0 000-1.5h-.253a.25.25 0 01-.244-.304l.459-2.066A1.75 1.75 0 009.253 9H9z" clip-rule="evenodd" />
      </svg>
    </div>
    <div class="ml-3 flex-1 md:flex md:justify-between">
      <p class="text-sm text-blue-700"><%= info %></p>
    </div>
  </div>
</div>

app/views/projects/_radio_group.html.erb
<fieldset data-controller="radio-selection">
  <legend class="text-base font-semibold leading-6 text-gray-900"><%= title %></legend>
  <div class="mt-4 grid grid-cols-1 gap-y-2 md:grid-cols-3 xl:grid-cols-5 sm:gap-x-2">
    <% items.each do |item| %>
      <!-- Active: "border-indigo-600 ring-2 ring-indigo-600", Not Active: "border-gray-300" -->
      <label data-action="click->radio-selection#toggle" data-radio-selection-target="option" class="min-h-[56px] relative flex cursor-pointer rounded-md bg-white p-2 focus:outline-none">
        <%= radio_button_tag(name, item, false, class: "form-radio sr-only", "data-action": "click->radio-selection#toggle", "data-radio-selection-target": "radio") %>
        <span class="flex flex-1">
          <span class="flex flex-col">
            <% if name == :app_type %>
              <span class="text-sm font-bold uppercase text-gray-900"><%= item %></span>
              <% if item == :standard %>
                <span class="label bg-red-100 text-red-800 rounded-md">default</span>
              <% end %>
              <span class="mt-1 flex items-center text-sm text-gray-500"><%= ::ProjectCreator::APP_TYPES[item] %></span>
            <% else %>
              <span class="text-sm font-bold uppercase text-gray-900"><%= item %></span>
              <% if ['7.0', '3.2.2', 'sqlite'].include?(item)  %>
                <span class="label bg-red-100 text-red-800 rounded-md">default</span>
              <% end %>
            <% end %>
          </span>
        </span>
        <!-- Not Checked: "invisible" -->
        <svg data-radio-selection-target="check" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
          <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.857-9.809a.75.75 0 00-1.214-.882l-3.483 4.79-1.88-1.88a.75.75 0 10-1.06 1.061l2.5 2.5a.75.75 0 001.137-.089l4-5.5z" clip-rule="evenodd"/>
        </svg>
        <!--
          Active: "border", Not Active: "border-2"
          Checked: "border-indigo-600", Not Checked: "border-transparent"
        -->
        <span class="pointer-events-none absolute -inset-px rounded-lg border-2" aria-hidden="true"></span>
      </label>
    <% end %>
  </div>
</fieldset>

app/views/projects/_warning.html.erb
<div class="rounded-md bg-yellow-50 p-4 mt-2">
  <div class="flex">
    <div class="flex-shrink-0">
      <svg class="h-5 w-5 text-yellow-400" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
        <path fill-rule="evenodd" d="M8.485 2.495c.673-1.167 2.357-1.167 3.03 0l6.28 10.875c.673 1.167-.17 2.625-1.516 2.625H3.72c-1.347 0-2.189-1.458-1.515-2.625L8.485 2.495zM10 5a.75.75 0 01.75.75v3.5a.75.75 0 01-1.5 0v-3.5A.75.75 0 0110 5zm0 9a1 1 0 100-2 1 1 0 000 2z" clip-rule="evenodd"/>
      </svg>
    </div>
    <div class="ml-3">
      <h3 class="text-sm font-medium text-yellow-800">Warning!</h3>
      <div class="mt-2 text-sm text-yellow-700">
        <p><%= warning %></p>
      </div>
    </div>
  </div>
</div>

app/views/projects/new.html.erb
<main class="h-screen w-full">
  <div class="pt-28 w-[80%] mx-auto h-full overflow-y-scroll no-scrollbar">
    <div class="flex flex-col items-center justify-center border-b border-b-gray-400 pb-4 border-dashed">
      <h2 class="text-gray-600 text-2xl py-4">
        <span class="font-extrabold text-2xl text-center">Rails App Generator:</span> Jumpstart Your Development Journey
      </h2>
      <p class="text-xl text-gray-500 text-center w-[80%]">
        Generate Rails applications without the command-line. This tool is a simplified interface to select the
        configurations you need in just a few clicks.
      </p>
    </div>
    <%= form_with url: projects_path, data: { turbo: false, controller: 'submit-form', action: 'submit->submit-form#handleFormSubmit' }, class: "px-2 py-16" do %>
      <div class="mb-6">
        <div class="mb-6">
          <%= render 'radio_group', name: :app_type, items: @supported_app_types, title: "App Type (Optional)" %>
        </div>

        <div class="mb-6">
          <%= render 'radio_group', name: :rails_version, items: @supported_rails_versions, title: "Rails Version (Optional)" %>
        </div>

        <div class="mb-6">
          <%= render 'radio_group', name: :ruby_version, items: @supported_ruby_versions, title: "Ruby Version (Optional)" %>
        </div>

        <div class="mb-6">
          <%= render 'radio_group', name: :database, items: @supported_databases, title: "Database Type (Optional)" %>
        </div>

        <p class="text-xl text-gray-400 border-dashed border border-t-gray-300 p-6">CSS & JS Processor options coming
          soon...</p>
      </div>

      <div class="absolute bottom-0 left-0 right-0 bg-transparent flex items-center justify-center py-4 over">
        <%= submit_tag "Generate", class: "bg-red-800 uppercase cursor-pointer ring-2 ring-inset ring-red-800 hover:bg-red-800 hover:text-white text-xl text-white font-semibold py-2 px-10 rounded-md transition-all ease-in-out duration-500 hover:px-12 hover:py-4" %>
      </div>
      <div>
        <h3 class="text-2xl py-2 text-gray-600 font-extrabold">Quick Start Guide:</h3>
        <div class="bg-gray-100 flex flex-col justify-center items-start p-8 rounded-md mb-2">
          <p><code>cd</code> into your generated project's directory.</p>
          <p>Run <code>bundle install</code> to install required gems.</p>
          <p>Open <code>config/database.yml</code> and update the database configurations as needed.</p>
          <p>Run the following commands to set up your database:</p>
          <p><code>rails db:prepare</code></p>
          <p><code>rails db:migrate</code></p>
          <p>Start your server with <code>rails s</code>.</p>
          <p>Open your browser and navigate to <code>http://localhost:3000</code> to see your new application in action!
          </p>
        </div>
      </div>
    <% end %>
  </div>
</main>